name: ReaPack-Index
on:
  push:
    branches: [ main, master ]
jobs:
  reapack-index:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'
          
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc
          gem install reapack-index
        
      - name: Configure Git
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          
      - name: Build and Commit index.xml
        run: reapack-index --name "AikyaLabs Simple ChordTrack" --commit
        
      - name: Push changes
        run: git push
